[logs]
level = "info"

[server]
http_port = 8080
[database]
host = "localhost"
port = 5435
user = "postgres"
password = "postgres"
dbname = "smk_userservice"
sslmode = "disable"

[jwt]
secret = "your-secret-key-change-in-production"
