version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: smk-userservice-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smk_userservice
    ports:
      - "5435:5432"
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    networks:
      - smk-userservice-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    container_name: smk-userservice-migrate
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    networks:
      - smk-userservice-network
    command: [
      "-path", "/migrations",
      "-database", "postgres://postgres:postgres@postgres:5432/smk_userservice?sslmode=disable",
      "up"
    ]
    restart: on-failure

networks:
  smk-userservice-network:
    driver: bridge
