global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'smk-userservice'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          service: 'userservice'
          environment: 'local'
